name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Gunakan versi terbaru (v4) agar file main.py terbaca dengan benar
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Login ke Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: dapurspl
        password: ${{ secrets.DOCKERPW }}

    # 3. Build dan Push menggunakan Action resmi (Lebih Cepat & Stabil)
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # PASTIKAN TAG INI SAMA DENGAN YANG DI CLOUD RUN
        tags: dapurspl/new2026:latest
